#include <math.h>

template<typename numericT>
class vector2
{
public:
    numericT x;
    numericT y;
    vector2();
    vector2(numericT value);
    vector2(numericT x,numericT y); 
    vector2(vector2& copy);
    vector2 add(vector2& b);
    void add_eq(vector2& b);
    static vector2 add(vector2& a,vector2& b);
    vector2 operator+(vector2& b);
    void operator+=(vector2& b);
    vector2 sub(vector2& b);
    void sub_eq(vector2& b);
    static vector2 sub(vector2& a,vector2& b);
    vector2 operator-(vector2& b);
    void operator-=(vector2& b);
    vector2 mul(vector2& b);
    void mul_eq(vector2& b);
    static vector2 mul(vector2& a,vector2& b);
    vector2 operator*(vector2& b);
    void operator*=(vector2& b);
    vector2 div(vector2& b);
    void div_eq(vector2& b);
    static vector2 div(vector2& a,vector2& b);
    vector2 operator/(vector2& b);
    void operator/=(vector2& b);
    vector2 floor_c();
    void floor_c_eq();
    static vector2 floor_c(vector2& a);
    vector2 round_c();
    void round_c_eq();
    static vector2 round_c(vector2& a);
    vector2 ceil_c();
    void ceil_c_eq();
    static vector2 ceil_c(vector2& a);
    vector2 min_c(vector2& b); //returns the min of each component
    void min_c_eq(vector2& b);
    static vector2 min_c(vector2& a,vector2& b);
    vector2 min_l(vector2& b); //returns the vector with min length
    void min_l_eq(vector2& b);
    static vector2 min_l(vector2& a,vector2& b);
    vector2 max_c(vector2& b); //returns the max of each component
    void max_c_eq(vector2& b);
    static vector2 max_c(vector2& a,vector2& b);
    vector2 max_l(vector2& b); //returns the vector with max length
    void max_l_eq(vector2& b);
    static vector2 max_l(vector2& a,vector2& b);
    numericT length(vector2& b);
    void length_c_eq(vector2& b);
    static numericT length(vector2& a,vector2& b);
    numericT det();
    void det_c_eq();
    static numericT det(vector2& a);
    vector2 normal();
    static vector2 normal(vector2& a);
    void normalize();
    numericT dot(vector2& b);
    void dot_c_eq(vector2& b);
    static numericT dot(vector2& a,vector2& b);
    void operator=(vector2& a);
    bool equals(vector2& b);
    static bool equals(vector2& a,vector2& b);
    bool any_equals(vector2& b);
    static bool any_equals(vector2& a,vector2& b);
    bool equals_l(vector2& a);
    static bool equals_l(vector2& a,vector2& b);
    vector2 add(numericT b);
    void add_eq(numericT b);
    static vector2 add(vector2& a,numericT b);
    vector2 operator+(numericT b);
    void operator+=(numericT b);
    vector2 sub(numericT b);
    void sub_eq(numericT b);
    static vector2 sub(vector2& a,numericT b);
    vector2 operator-(numericT b);
    void operator-=(numericT b);
    vector2 mul(numericT b);
    void mul_eq(numericT b);
    static vector2 mul(vector2& a,numericT b);
    vector2 operator*(numericT b);
    void operator*=(numericT b);
    vector2 div(numericT b);
    void div_eq(numericT b);
    static vector2 div(vector2& a,numericT b);
    vector2 operator/(numericT b);
    void operator/=(numericT b);
    numericT length(numericT b);
    void length_c_eq(numericT b);
    void operator=(numericT& a);
    bool equals(numericT b);
    static bool equals(vector2& a,numericT b);
    bool any_equals(numericT b);
    static bool any_equals(vector2& a,numericT b);
    bool isLargerThan_l(vector2& b);
    bool operator>(vector2& b);
    static bool isLargerThan_l(vector2& a,vector2& b);
    bool isLargerThanOrEqual_l(vector2& b);
    bool operator>=(vector2& b);
    static bool isLargerThanOrEqual_l(vector2& a,vector2& b);
    bool isSmallerThan_l(vector2& b);
    bool operator<(vector2& b);
    static bool isSmallerThan_l(vector2& a,vector2& b);
    bool isSmallerThanOrEqual_l(vector2& b);
    bool operator<=(vector2& b);
    static bool isSmallerThanOrEqual_l(vector2& a,vector2& b);  
};
